# Generated by Django 5.0.7 on 2024-07-30 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Single_Todo',
            new_name='SingleTodo',
        ),
    ]
